import './globals.css'
import './style/style.css'
import './style/responsive.css'
import './style/bootstarp.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next Js',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      
      {/* <!-- jQery --> */}
      {/* <Script  src="/../public/js/jquery-3.4.1.min.js"></Script> */}
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
     
      {/* <!-- popper js --> */}
      {/* <Script  src="/../public/assets/js/popper.min.js"></Script> */}

      {/* <!-- bootstrap js --> */}
      {/* <Script  src="/../public/assets/js/bootstrap.js"></Script> */}
      {/* <!-- custom js --> */}
      {/* <Script  src="/../public/assets/js/custom.js"></Script> */}
      </body>
    </html>
  )
}
